[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src/"]
include = ["tfm*"]

[project]
name = "tfm"
version = "0.1.0"
requires-python = ">= 3.12"
